'\" t
.TH adasockets-config 1 "22 May 2000"
.SH NAME
adasockets-config \- script to get information about the installed AdaSockets
library
.SH SYNOPSIS
.B adasockets-config
[\-\-version] [\-\-libs] [\-\-cflags]
.SH DESCRIPTION
.B adasockets-config
will echo a line on standard output with appropriate flags for
.B gnatmake .
.SH "SEE ALSO"
.BR gnatmake (1), 
.SH AUTHORS
Samuel Tardieu <sam@inf.enst.fr>
